### PR TITLE
Fixes cross attention tests and refactors code

### LINKED ISSUE #1968: [issue] Heap buffer overflow detected during AddressSanitizer run
```
Run ASAN_OPTIONS=detect_leaks=1:print_stats=1 tests/ctranslate2_test tests/data
[==========] Running 181 tests from 18 test suites.
[----------] Global test environment set-up.
[----------] 3 tests from CrossAttentionTest
[ RUN      ] CrossAttentionTest.MultiQueryAttention
=================================================================
==6117==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x50e0000000d8 at pc 0x7f1a8bb80209 bp 0x7f1a843f2540 sp 0x7f1a843f2530
...
```

job: https://github.com/OpenNMT/CTranslate2/actions/runs/20763920526/job/59625551046
PR: https://github.com/OpenNMT/CTranslate2/pull/1903

### PR DESCRIPTION
**Pull request by jordimas**
Changes
- Encapsulates K norm logic in its own method
-  Fixes #1968 error in the test
- Removes _merge_time_and_head_dims code path

### CODE REVIEW

**Comment by sssshhhhhh** [comment]
I went digging through old commits
https://github.com/OpenNMT/CTranslate2/pull/1282 removed multi_query flag from attention spec but kept some c++ code for backwards compatability.
https://github.com/OpenNMT/CTranslate2/pull/1451 introduced _merge_time_and_head_dims to fix mqa with rpe
https://github.com/OpenNMT/CTranslate2/pull/1599 I think misunderstood the backwards compatability and started using multi_query again which isn't set

I think it would be safe to redefine multi_query() as num_heads_kv == 1 && !_tensor_parallel; and _merge_time_and_head_dims = multi_query() && !_relative_etc.

File: src/layers/attention.cc [hunk 1]
```diff
@@ -336,18 +336,22 @@ namespace ctranslate2 {
       return _d_model;
     }
 
+    void MultiHeadAttention::apply_k_norm(StorageView& keys_proj) const {
+      if (_k_norm) {
+        StorageView keys_normed(keys_proj.dtype(), keys_proj.device());
+        (*_k_norm)(keys_proj, keys_normed);
+        keys_proj = std::move(keys_normed);
```
Comment (sssshhhhhh) [inline src/layers/attention.cc]: Layernorm/rmsnorm can be in place

File: tests/attention_test.cc [hunk 2]
```diff
@@ -17,12 +17,14 @@ class MockModel : public models::Model {
     register_variable("attn/linear_2/weight",
                       StorageView({d_model, num_heads * d_head}, DataType::FLOAT32));
     register_variable("attn/q_norm/gamma",
-                      StorageView({d_head}, std::vector<float>(d_head, 1.0f)));
+                      StorageView({d_model}, std::vector<float>(d_model, 1.0f)));
```
Comment (sssshhhhhh) [inline tests/attention_test.cc]: Wasn't d_head correct?

**Comment by jordimas** [comment]
> I went digging through old commits #1282 removed multi_query flag from attention spec but kept some c++ code for backwards compatability. #1451 introduced _merge_time_and_head_dims to fix mqa with rpe #1599 I think misunderstood the backwards compatability and started using multi_query again which isn't set
> 
> I think it would be safe to redefine multi_query() as num_heads_kv == 1 && !_tensor_parallel; and _merge_time_and_head_dims = multi_query() && !_relative_etc.

My understanding is that your comment is linked to self_attention not to cross attention. Self attention is outside the scope of this PR.. I will then create a ticket to:
- Create unit tests for self_attention 
- Implement your safe net
- Remove multi_query in attention.cc and attention.h

Does this work? If does, I will create a ticket for this. Thanks

**Comment by sssshhhhhh** [comment]
Yes mostly relevant to self, since there's probably no chance of anyone doing cross attn & rpe & mqa these days. And now it's all 4d there won't be any issues
